image: node:latest

before_script:
  - npm install

stages:
  - build

build:
  stage: pages
  cache:
    paths:
    - node_modules/
  script:
  - npm run build
  - npm run start
  artifacts:
    paths:
    - dist
  only:
  - master
