version: "3.3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs:/var/log/nginx/

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - './back:/back'
      - /back/data
      - /back/db

  back:
    container_name: back
    build: ./back
    volumes:
      - './back:/back'
      - '/back/node_modules'
    environment:
      - MONGO_URI=mongodb://mongodb:27017/wssmm
    ports:
      - "7000:7000" 
    depends_on:
      - mongodb

  front:
    container_name: front
    build: ./front
    volumes:
      - './front:/front'
      - '/front/node_modules'
    ports:
      - "3000:3000"
  
  
  
