version: "3.3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - .:/app/back/data
      - ./db

  back:
    container_name: back
    build: ./back
    volumes:
      - '.:/app/back'
      - './node_modules'
    environment:
      - MONGO_URI=mongodb://mongodb:27017/wssmm
    ports:
      - "7000:7000" 
    depends_on:
      - mongodb

  wssmm:
    container_name: wssmm
    build: ./front
    volumes:
      - '.:/app/wssmm'
      - '/app/wssmm/node_modules'
    ports:
      - "3000:3000"
  
  
  
