version: "3.3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  back:
    container_name: back
    image: registry.gitlab.com/lowrider-fn/wssmm/back
    environment:
      - MONGO_URI=mongodb://mongodb:27017/wssmm
    restart: always
    ports:
      - "7000:7000" 
    depends_on:
      - mongo

  wssmm:
    container_name: wssmm
    image: registry.gitlab.com/lowrider-fn/wssmm/front
    restart: always
    ports:
      - "3000:3000"
  
  
  
